/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   SignalTypeCode.h
 * Author: 10256
 *
 * Created on 2017年2月9日, 下午7:31
 */

#ifndef SIGNALTYPECODE_H
#define SIGNALTYPECODE_H

/*********************************************************************************
* Define Device Number (Equal to the Source Address)
* 
 ********************************************************************************/
/*
*CAN1
*/
#define CAN1_DEVICE_VCU                                                           (101)
#define CAN1_DEVICE_MCU                                                          (102)
#define CAN1_DEVICE_BMS                                                           (103)
#define CAN1_DEVICE_CCU                                                           (105)
#define CAN1_DEVICE_DCDC                                                        (104)
#define CAN1_DEVICE_EPS                                                             (108)
#define CAN1_DEVICE_EPB                                                            (111)
#define CAN1_DEVICE_ACU                                                           (109)
#define CAN1_DEVICE_BCM                                                          (106)
#define CAN1_DEVICE_ICU                                                            (107)
#define CAN1_DEVICE_ESC                                                            (110)
#define CAN1_DEVICE_TPMS                                               (112)

/*
*CAN3
*/

#define CAN3_DEVICE_ACC                                                           (302)
#define CAN3_DEVICE_APS                                                            (303)

#if 0
#define CAN_DEVICE_MOTOR                                                       (0xEF)
#define CAN_DEVICE_BATTERY                                                     (0xF4)
#define CAN_DEVICE_DOOR                                                          (0xEC)
#define CAN_DEVICE_LIGHT                                                 (0x37)
#define CAN_DEVICE_VCU                                                             (0xD0)
#define CAN_DEVICE_ABS                                                              (0x0B)
#define CAN_DEVICE_AC                                                                (0xFD)
#endif

/*********************************************************************************
* Define J1939 Macro 
 ********************************************************************************/
#define CAN_MESSAGE_LENGTH                                                           (8)



/* Calculate Option Code */
#define CAN_OPCODE(dev, op)    (((dev)*10000)+(op))


/*********************************************************************************
* Define Option Code for Graphic  Module
*             Option Code                                 =                                                         (DeviceName << 16) | SPN         
********************************************************************************/
/* VCU information*/

#define OPCODE_VCU_VEHICLE_WARNING  CAN_OPCODE(CAN1_DEVICE_VCU,104)
#define OPCODE_VCU_GEAR_LEVEL_POS_STS      CAN_OPCODE(CAN1_DEVICE_VCU,105)
#define OPCODE_VCU_VEHICLE_STS     CAN_OPCODE(CAN1_DEVICE_VCU,106)
#define OPCODE_VCU_DCDCENABLECMD    CAN_OPCODE(CAN1_DEVICE_VCU,109)
#define OPCODE_VCU_BRAKE_PEDAL_STS    CAN_OPCODE(CAN1_DEVICE_VCU,110)
#define OPCODE_VCU_ROLLING_COUNTER CAN_OPCODE(CAN1_DEVICE_VCU,115)
#define OPCODE_VCU_POWERREDUCEREQ CAN_OPCODE(CAN1_DEVICE_VCU,201)
#define OPCODE_VCU_ALWCHARGESTS         CAN_OPCODE(CAN1_DEVICE_VCU,205)
#define OPCODE_VCU_KEYPOSITION     CAN_OPCODE(CAN1_DEVICE_VCU,207)
#define OPCODE_VCU_BRAKE_FAULT    CAN_OPCODE(CAN1_DEVICE_VCU,208)
#define OPCODE_VCU_IPAS_ALWENABLE      CAN_OPCODE(CAN1_DEVICE_VCU,209)
#define OPCODE_VCU_POWERON2REQ         CAN_OPCODE(CAN1_DEVICE_VCU,211)
#define OPCODE_VCU_POWERON2RESETREQ       CAN_OPCODE(CAN1_DEVICE_VCU,212)
#define OPCODE_VCU_MOTORWATERPUMP_WATER_INLETTEMP      CAN_OPCODE(CAN1_DEVICE_VCU,214)
#define OPCODE_VCU_MOTORWATERPUMP_WATER_OUTLETTEMP  CAN_OPCODE(CAN1_DEVICE_VCU,215)


/*MCU information*/
#define OPCODE_MCU_MOTOR_RPM          CAN_OPCODE(CAN1_DEVICE_MCU,101)
#define OPCODE_MCU_WARNING_LEVEL     CAN_OPCODE(CAN1_DEVICE_MCU,102)
#define OPCODE_MCU_DRVMOTORFAULTSTS       CAN_OPCODE(CAN1_DEVICE_MCU,103)
#define OPCODE_MCU_SELF_CHECK            CAN_OPCODE(CAN1_DEVICE_MCU,104)
#define OPCODE_MCU_MOTOR_RPM_FAULT        CAN_OPCODE(CAN1_DEVICE_MCU,105)
#define OPCODE_MCU_ACTUALTORQUEFB_F       CAN_OPCODE(CAN1_DEVICE_MCU,106)
#define OPCODE_MCU_ACTUALTORQUEFB  CAN_OPCODE(CAN1_DEVICE_MCU,108)
#define OPCODE_MCU_INSTANT_POWER     CAN_OPCODE(CAN1_DEVICE_MCU,111)
#define OPCODE_MCU_ROLLINGCOUNTER  CAN_OPCODE(CAN1_DEVICE_MCU,113)
#define OPCODE_MCU_MOTOR_TEMP        CAN_OPCODE(CAN1_DEVICE_MCU,201)
#define OPCODE_MCU_TEMP                                   CAN_OPCODE(CAN1_DEVICE_MCU,202)
#define OPCODE_MCU_MAINWIREVOLT              CAN_OPCODE(CAN1_DEVICE_MCU,203)
#define OPCODE_MCU_MAINWIRECURR               CAN_OPCODE(CAN1_DEVICE_MCU,204)



/*BMS information*/
#define OPCODE_BMS_WARNING_LEVEL      CAN_OPCODE(CAN1_DEVICE_BMS,101)
#define OPCODE_BMS_BATT_CHARGE_STS  CAN_OPCODE(CAN1_DEVICE_BMS,102)
#define OPCODE_BMS_SELF_CHECK      CAN_OPCODE(CAN1_DEVICE_BMS,103)
#define OPCODE_BMS_HIGHVOL_STS   CAN_OPCODE(CAN1_DEVICE_BMS,104)
#define OPCODE_BMS_BATT_SOC CAN_OPCODE(CAN1_DEVICE_BMS,113)
#define OPCODE_BMS_BATT_SOH CAN_OPCODE(CAN1_DEVICE_BMS,114)
#define OPCODE_BMS_ISO_RESSISTANCE_LEVEL CAN_OPCODE(CAN1_DEVICE_BMS,116)
#define OPCODE_BMS_ROLLINGCOUNTER   CAN_OPCODE(CAN1_DEVICE_BMS,122)
#define OPCODE_BMS_BATT_TOTAL_VOLT   CAN_OPCODE(CAN1_DEVICE_BMS,201)
#define OPCODE_BMS_BATT_TOTAL_CURR  CAN_OPCODE(CAN1_DEVICE_BMS,202)
#define OPCODE_BMS_REMAIN_MILE  CAN_OPCODE(CAN1_DEVICE_BMS,203)
#define OPCODE_BMS_REMAIN_ENERGY     CAN_OPCODE(CAN1_DEVICE_BMS,205)
#define OPCODE_BMS_BATT_MAX_TEMP     CAN_OPCODE(CAN1_DEVICE_BMS,401)
#define OPCODE_BMS_BATT_MIN_TEMP      CAN_OPCODE(CAN1_DEVICE_BMS,402)
#define OPCODE_BMS_REMAIN_CHARGE_TIME  CAN_OPCODE(CAN1_DEVICE_BMS,503)
#define OPCODE_BMS_CHARGE_AC_INPUT CAN_OPCODE(CAN1_DEVICE_BMS,505)
#define OPCODE_BMS_CHARGE_DC_INPUT CAN_OPCODE(CAN1_DEVICE_BMS,506)
#define OPCODE_BMS_CELLMAXVOLT  CAN_OPCODE(CAN1_DEVICE_BMS,601)
#define OPCODE_BMS_CELLMINVOLT   CAN_OPCODE(CAN1_DEVICE_BMS,603)
#define OPCODE_BMS_CELLAVGVOLT   CAN_OPCODE(CAN1_DEVICE_BMS,605)
#define OPCODE_BMS_CELLMAXVOLTNUMBER   CAN_OPCODE(CAN1_DEVICE_BMS,607)
#define OPCODE_BMS_CELLMINVOLTNUMBER    CAN_OPCODE(CAN1_DEVICE_BMS,608)






/*CCU information*/
#define OPCODE_CCU_HARDWARE_STS        CAN_OPCODE(CAN1_DEVICE_CCU,104)
#define OPCODE_CCU_CHARGER_TEMP_WARNING    CAN_OPCODE(CAN1_DEVICE_CCU,105)
#define OPCODE_CCU_VOLT_INPUT_STS       CAN_OPCODE(CAN1_DEVICE_CCU,106)
#define OPCODE_CCU_START_STS CAN_OPCODE(CAN1_DEVICE_CCU,107)
#define OPCODE_CCU_COMMUNCATION_STS      CAN_OPCODE(CAN1_DEVICE_CCU,108)
#define OPCODE_CCU_OUTPUTS_STS    CAN_OPCODE(CAN1_DEVICE_CCU,109)


/*DCDC information*/    
#define OPCODE_DCDC_WORKING_STS         CAN_OPCODE(CAN1_DEVICE_DCDC,101)
#define OPCODE_DCDC_ROLLINGCOUNTER CAN_OPCODE(CAN1_DEVICE_DCDC,115)


/*EPS information*/
#define OPCODE_EPS_SAS_STEERWHEELANGLE   CAN_OPCODE(CAN1_DEVICE_EPS,101)
#define OPCODE_EPS_SAS_STEERWHEELROTSPD CAN_OPCODE(CAN1_DEVICE_EPS,102)
#define OPCODE_EPS_SAS_STEERINGANGLEVALIDDATA       CAN_OPCODE(CAN1_DEVICE_EPS,104)
#define OPCODE_EPS_SAS_STEERINGANGLESPEEDVALIDDATA    CAN_OPCODE(CAN1_DEVICE_EPS,105)
#define OPCODE_EPS_SAS_FAILURESTS CAN_OPCODE(CAN1_DEVICE_EPS,106)
#define OPCODE_EPS_FAULT  CAN_OPCODE(CAN1_DEVICE_EPS,107)
#define OPCODE_EPS_SAS_STEERINGTORQUEVALIDDATA    CAN_OPCODE(CAN1_DEVICE_EPS,109)
#define OPCODE_EPS_SAS_STEERINGTORQUE      CAN_OPCODE(CAN1_DEVICE_EPS,110)
#define OPCODE_EPS_ROLLINGCOUNTER     CAN_OPCODE(CAN1_DEVICE_EPS,112)



/*EPB information*/
#define OPCODE_EPB_ACTUATORSTATE         CAN_OPCODE(CAN1_DEVICE_EPB,102)
#define OPCODE_EPB_MANUALPARKINGKEY         CAN_OPCODE(CAN1_DEVICE_EPB,104)
#define OPCODE_EPB_MILLAMP    CAN_OPCODE(CAN1_DEVICE_EPB,106)
#define OPCODE_EPB_PARKINGLAMP   CAN_OPCODE(CAN1_DEVICE_EPB,107)
#define OPCODE_EPB_ROLLINGCOUNTER     CAN_OPCODE(CAN1_DEVICE_EPB,114)


/*ACU information*/
#define OPCODE_ACU_CRASHOUTPUTSTS    CAN_OPCODE(CAN1_DEVICE_ACU,101)
#define OPCODE_ACU_AIRBAGFAILSTS CAN_OPCODE(CAN1_DEVICE_ACU,102)
#define OPCODE_ACU_DRVSEATBELTRST      CAN_OPCODE(CAN1_DEVICE_ACU,104)
#define OPCODE_ACU_PSSEATBELTRST CAN_OPCODE(CAN1_DEVICE_ACU,105)
#define OPCODE_ACU_OC_PPD_STATUS        CAN_OPCODE(CAN1_DEVICE_ACU,106)
#define OPCODE_ACU_ROLLINGCOUNTER    CAN_OPCODE(CAN1_DEVICE_ACU,108)


/*BCM information*/
#define OPCODE_BCM_FAULT         CAN_OPCODE(CAN1_DEVICE_BCM,101)
#define OPCODE_BCM_KEYPOSITION_ON2   CAN_OPCODE(CAN1_DEVICE_BCM,103)
#define OPCODE_BCM_ACCHGLOCKSTATUS CAN_OPCODE(CAN1_DEVICE_BCM,105)
#define OPCODE_BCM_ACCHGCOVERSTATUS       CAN_OPCODE(CAN1_DEVICE_BCM,106)
#define OPCODE_BCM_DCCHGCOVERSTATUS       CAN_OPCODE(CAN1_DEVICE_BCM,107)
#define OPCODE_BCM_BRAKE_FLUID_LEVEL        CAN_OPCODE(CAN1_DEVICE_BCM,110)
#define OPCODE_BCM_OUTSIDE_TEMP        CAN_OPCODE(CAN1_DEVICE_BCM,114)
#define OPCODE_BCM_LBMS_SOC         CAN_OPCODE(CAN1_DEVICE_BCM,115)
#define OPCODE_BCM_ES_WORKSTS    CAN_OPCODE(CAN1_DEVICE_BCM,117)
#define OPCODE_BCM_ES_FAULT  CAN_OPCODE(CAN1_DEVICE_BCM,118)
#define OPCODE_BCM_MMI_AUTOHOLDENABLE         CAN_OPCODE(CAN1_DEVICE_BCM,119)
#define OPCODE_BCM_ALARM_MODE CAN_OPCODE(CAN1_DEVICE_BCM,201)
#define OPCODE_BCM_PARKING_LIGHT_REMINDER   CAN_OPCODE(CAN1_DEVICE_BCM,202)
#define OPCODE_BCM_KEY_REMINDER        CAN_OPCODE(CAN1_DEVICE_BCM,203)
#define OPCODE_BCM_TURN_RIGHT_STS    CAN_OPCODE(CAN1_DEVICE_BCM,204)
#define OPCODE_BCM_TURN_LEFT_STS        CAN_OPCODE(CAN1_DEVICE_BCM,205)
#define OPCODE_BCM_HAZARD_STS    CAN_OPCODE(CAN1_DEVICE_BCM,206)
#define OPCODE_BCM_PARKING_LIGHT_STS        CAN_OPCODE(CAN1_DEVICE_BCM,207)
#define OPCODE_BCM_HIGH_BEAM_STS      CAN_OPCODE(CAN1_DEVICE_BCM,208)
#define OPCODE_BCM_LOW_BEAM_STS       CAN_OPCODE(CAN1_DEVICE_BCM,209)
#define OPCODE_BCM_FL_DOOR_STS   CAN_OPCODE(CAN1_DEVICE_BCM,210)
#define OPCODE_BCM_FR_DOOR_STS  CAN_OPCODE(CAN1_DEVICE_BCM,211)
#define OPCODE_BCM_HOOD_STS         CAN_OPCODE(CAN1_DEVICE_BCM,212)
#define OPCODE_BCM_RR_DOOR_STS CAN_OPCODE(CAN1_DEVICE_BCM,213)
#define OPCODE_BCM_RL_DOOR_STS  CAN_OPCODE(CAN1_DEVICE_BCM,214)
#define OPCODE_BCM_BACK_DOOR_STS      CAN_OPCODE(CAN1_DEVICE_BCM,215)
#define OPCODE_BCM_REAR_FOG_STS         CAN_OPCODE(CAN1_DEVICE_BCM,216)
#define OPCODE_BCM_FRONT_FOG_STS       CAN_OPCODE(CAN1_DEVICE_BCM,217)
#define OPCODE_BCM_REAR_DEFROSTER    CAN_OPCODE(CAN1_DEVICE_BCM,218)
#define OPCODE_BCM_FRONT_COVER_LOCK_STS        CAN_OPCODE(CAN1_DEVICE_BCM,220)
#define OPCODE_BCM_KEYIN_STS         CAN_OPCODE(CAN1_DEVICE_BCM,221)
#define OPCODE_BCM_DRL_STS    CAN_OPCODE(CAN1_DEVICE_BCM,222)
#define OPCODE_BCM_FL_DOOR_LOCK_STS         CAN_OPCODE(CAN1_DEVICE_BCM,223)
#define OPCODE_BCM_FR_DOOR_LOCK_STS        CAN_OPCODE(CAN1_DEVICE_BCM,224)
#define OPCODE_BCM_RR_DOOR_LOCK_STS        CAN_OPCODE(CAN1_DEVICE_BCM,225)
#define OPCODE_BCM_RL_DOOR_LOCK_STS        CAN_OPCODE(CAN1_DEVICE_BCM,226)
#define OPCODE_BCM_BACK_DOOR_LOCK_STS   CAN_OPCODE(CAN1_DEVICE_BCM,227)
#define OPCODE_BCM_POSITION_LIGHT_STS       CAN_OPCODE(CAN1_DEVICE_BCM,229)
#define OPCODE_BCM_TURN_LEFT_SWITCH_STS         CAN_OPCODE(CAN1_DEVICE_BCM,234)
#define OPCODE_BCM_TURN_RIGHT_SWITCH_STS     CAN_OPCODE(CAN1_DEVICE_BCM,235)


/*ICU information*/
#define OPCODE_ICU_FAULT  CAN_OPCODE(CAN1_DEVICE_ICU,101)
#define OPCODE_ICU_ALLOWBCMON3_ON CAN_OPCODE(CAN1_DEVICE_ICU,103)
#define OPCODE_ICU_AIRBAG_STATUS CAN_OPCODE(CAN1_DEVICE_ICU,104)
#define OPCODE_ICU_DRIVE_MODE     CAN_OPCODE(CAN1_DEVICE_ICU,106)
#define OPCODE_ICU_TOTAL_METER    CAN_OPCODE(CAN1_DEVICE_ICU,108)
#define OPCODE_ICU_APS_ENABLE_REQ      CAN_OPCODE(CAN1_DEVICE_ICU,201)
#define OPCODE_ICU_APS_WORK_STS  CAN_OPCODE(CAN1_DEVICE_ICU,202)


/*ESC informations*/
#define OPCODE_ESC_FL_WHEEL_SPEED_RC        CAN_OPCODE(CAN1_DEVICE_ESC,301)
#define OPCODE_ESC_FR_WHEEL_SPEED_RC        CAN_OPCODE(CAN1_DEVICE_ESC,302)
#define OPCODE_ESC_RL_WHEEL_SPEED_RC        CAN_OPCODE(CAN1_DEVICE_ESC,303)
#define OPCODE_ESC_RR_WHEEL_SPEED_RC       CAN_OPCODE(CAN1_DEVICE_ESC,304)
#define OPCODE_ESC_FL_WHEEL_SPEED_RC_STS         CAN_OPCODE(CAN1_DEVICE_ESC,305)
#define OPCODE_ESC_FR_WHEEL_SPEED_RC_STS        CAN_OPCODE(CAN1_DEVICE_ESC,306)
#define OPCODE_ESC_RL_WHEEL_SPEED_RC_STS        CAN_OPCODE(CAN1_DEVICE_ESC,307)
#define OPCODE_ESC_RR_WHEEL_SPEED_RC_STS        CAN_OPCODE(CAN1_DEVICE_ESC,308)
#define OPCODE_ESC_ESC4_ROLLING_COUNTER          CAN_OPCODE(CAN1_DEVICE_ESC,309)
#define OPCODE_ESC_EBD_FAILD CAN_OPCODE(CAN1_DEVICE_ESC,403)
#define OPCODE_ESC_ABS_FAILD  CAN_OPCODE(CAN1_DEVICE_ESC,404)
#define OPCODE_ESC_ESP_ACTIVE         CAN_OPCODE(CAN1_DEVICE_ESC,406)
#define OPCODE_ESC_TCS_FAILD  CAN_OPCODE(CAN1_DEVICE_ESC,407)
#define OPCODE_ESC_ESP_FAILD   CAN_OPCODE(CAN1_DEVICE_ESC,408)
#define OPCODE_ESC_VEHICLE_SPEED CAN_OPCODE(CAN1_DEVICE_ESC,409)
#define OPCODE_ESC_ESP_FUNCTIONSTATUS       CAN_OPCODE(CAN1_DEVICE_ESC,411)
#define OPCODE_ESC_VEHICLE_SPEED_VAILD      CAN_OPCODE(CAN1_DEVICE_ESC,412)
#define OPCODE_ESC_HHC_ERROR_STATUS CAN_OPCODE(CAN1_DEVICE_ESC,418)
#define OPCODE_ESC_AVH_DISP_WITHOUT_SEATBELT        CAN_OPCODE(CAN1_DEVICE_ESC,420)
#define OPCODE_ESC_ESC5_ROLLING_COUNTER          CAN_OPCODE(CAN1_DEVICE_ESC,422)


/*TPMS*/
#define OPCODE_TPMS_TIREPOSITION CAN_OPCODE(CAN1_DEVICE_TPMS,101)
#define OPCODE_TPMS_SINGLETIRESIGSTS  CAN_OPCODE(CAN1_DEVICE_TPMS,102)
#define OPCODE_TPMS_SYSTEMSTS       CAN_OPCODE(CAN1_DEVICE_TPMS,103)
#define OPCODE_TPMS_SINGLEFLATTIRESTS         CAN_OPCODE(CAN1_DEVICE_TPMS,104)
#define OPCODE_TPMS_SINGLETIREPRESSSTS       CAN_OPCODE(CAN1_DEVICE_TPMS,105)
#define OPCODE_TPMS_SINGLETIRETEMPSTS       CAN_OPCODE(CAN1_DEVICE_TPMS,106)
#define OPCODE_TPMS_SINGLESENSORASSBATTSTS     CAN_OPCODE(CAN1_DEVICE_TPMS,107)
#define OPCODE_TPMS_SINGLETIREPRESS    CAN_OPCODE(CAN1_DEVICE_TPMS,108)
#define OPCODE_TPMS_SINGLETIRETEMP    CAN_OPCODE(CAN1_DEVICE_TPMS,110)


/*CAN3*/
/*ACC*/
#define OPCODE_ACC_ACCMODE CAN_OPCODE(CAN3_DEVICE_ACC,103)
#define OPCODE_ACC_ROLLINGCOUNTER    CAN_OPCODE(CAN3_DEVICE_ACC,109)

/*APS*/
#define OPCODE_APS_WORKSTS    CAN_OPCODE(CAN3_DEVICE_APS,102)
#define OPCODE_APS_PARKINGSTS        CAN_OPCODE(CAN3_DEVICE_APS,103)
#define OPCODE_APS_PDC_ENSTS          CAN_OPCODE(CAN3_DEVICE_APS,104)
#define OPCODE_APS_FINDPARKSPACEENSTS        CAN_OPCODE(CAN3_DEVICE_APS,111)
#define OPCODE_APS_DISPLAYINFO       CAN_OPCODE(CAN3_DEVICE_APS,113)
#define OPCODE_APS_ROLLINGCOUNTER     CAN_OPCODE(CAN3_DEVICE_APS,115)
#define OPCODE_APS_FINDPARKSPACERST   CAN_OPCODE(CAN3_DEVICE_APS,201)
#define OPCODE_APS_PARKSPACENUM          CAN_OPCODE(CAN3_DEVICE_APS,202)
#define OPCODE_APS_PARKSPACE1TYPE        CAN_OPCODE(CAN3_DEVICE_APS,203)
#define OPCODE_APS_PARKSPACE1RANGE    CAN_OPCODE(CAN3_DEVICE_APS,204)
#define OPCODE_APS_PARKSPACE2TYPE        CAN_OPCODE(CAN3_DEVICE_APS,205)
#define OPCODE_APS_PARKSPACE2RANGE    CAN_OPCODE(CAN3_DEVICE_APS,206)
#define OPCODE_APS_FRONTPDC1DETECTDIST   CAN_OPCODE(CAN3_DEVICE_APS,301)
#define OPCODE_APS_FRONTPDC1FAULTSTS         CAN_OPCODE(CAN3_DEVICE_APS,302)
#define OPCODE_APS_FRONTPDC2DETECTDIST   CAN_OPCODE(CAN3_DEVICE_APS,303)
#define OPCODE_APS_FRONTPDC2FAULTSTS         CAN_OPCODE(CAN3_DEVICE_APS,304)
#define OPCODE_APS_FRONTPDC3DETECTDIST   CAN_OPCODE(CAN3_DEVICE_APS,305)
#define OPCODE_APS_FRONTPDC3FAULTSTS         CAN_OPCODE(CAN3_DEVICE_APS,306)
#define OPCODE_APS_FRONTPDC4DETECTDIST   CAN_OPCODE(CAN3_DEVICE_APS,307)
#define OPCODE_APS_FRONTPDC4FAULTSTS         CAN_OPCODE(CAN3_DEVICE_APS,308)
#define OPCODE_APS_REARPDC1DETECTDIST      CAN_OPCODE(CAN3_DEVICE_APS,401)
#define OPCODE_APS_REARPDC1FAULTSTS   CAN_OPCODE(CAN3_DEVICE_APS,402)
#define OPCODE_APS_REARPDC2DETECTDIST      CAN_OPCODE(CAN3_DEVICE_APS,403)
#define OPCODE_APS_REARPDC2FAULTSTS   CAN_OPCODE(CAN3_DEVICE_APS,404)
#define OPCODE_APS_REARPDC3DETECTDIST      CAN_OPCODE(CAN3_DEVICE_APS,405)
#define OPCODE_APS_REARPDC3FAULTSTS   CAN_OPCODE(CAN3_DEVICE_APS,406)
#define OPCODE_APS_REARPDC4DETECTDIST      CAN_OPCODE(CAN3_DEVICE_APS,407)
#define OPCODE_APS_REARPDC4FAULTSTS   CAN_OPCODE(CAN3_DEVICE_APS,408)
#define OPCODE_APS_LEFTPDC1DETECTDIST        CAN_OPCODE(CAN3_DEVICE_APS,501)
#define OPCODE_APS_LEFTPDC1FAULTSTS    CAN_OPCODE(CAN3_DEVICE_APS,502)
#define OPCODE_APS_LEFTPDC2DETECTDIST        CAN_OPCODE(CAN3_DEVICE_APS,503)
#define OPCODE_APS_LEFTPDC2FAULTSTS    CAN_OPCODE(CAN3_DEVICE_APS,504)
#define OPCODE_APS_RIGHTPDC1DETECTDIST    CAN_OPCODE(CAN3_DEVICE_APS,505)
#define OPCODE_APS_RIGHTPDC1FAULTSTS CAN_OPCODE(CAN3_DEVICE_APS,506)
#define OPCODE_APS_RIGHTPDC2DETECTDIST    CAN_OPCODE(CAN3_DEVICE_APS,507)
#define OPCODE_APS_RIGHTPDC2FAULTSTS CAN_OPCODE(CAN3_DEVICE_APS,508)


#endif /* SIGNALTYPECODE_H */

